#!/usr/bin/perl
use strict;
use warnings;
use Data::Dumper;

use Module::CoreList;

die "USAGE: perl $0 Some::Package Hoopy-Frood\n" unless @ARGV;
die Dumper(\%Module::CoreList::released) if $ARGV[0] eq '--dump';

s/-/::/g for @ARGV;

print "Packages (@ARGV) included in the Perl core:\n";

my $in_core = {};

# Build a perl version => module version list.
for my $p (@ARGV) {
    for my $v ( keys %Module::CoreList::released ) {
        if( $Module::CoreList::version{$v}{$p} ) {
            $in_core->{$p}{$v} = $Module::CoreList::version{$v}{$p};
        }
#        else {
#            warn "Package, $p, is not in perl version $v.\n";
#        }
    }
}

warn Data::Dumper->new([$in_core])->Indent(1)->Terse(1)->Sortkeys(1)->Dump;
