#!/usr/bin/env perl
use strict;
use warnings;

use Acme::CPANAuthors;
use HTTP::Simple;
use HTML::TreeBuilder;

# Fetch all author modules
my $url = 'https://www.cpan.org/modules/01modules.index.html';
my $content = get $url;
print "URL: $url fetched.\n";

# Parse the content into a tree
my $tree = HTML::TreeBuilder->new();
$tree->parse($content);
$tree->eof;

# Accumulate the text bits as lines
my $text = '';
for my $pre ( $tree->look_down( _tag => 'pre' ) ) {
    $text .= $pre->as_text;
}
my @lines = split /\n/, $text;

# Bucket for the authors and their avatars
my %authors = ();

for my $line ( @lines ) {
    # module, author, distribution, size, uploaded
    my @parts = $line =~ /^(\w+)\s+([A-Z]+)\s+(\S+)\s+(\d+\w)\s+(.*?)\s*\+?\s*$/g;
    next unless $parts[0];
    $authors{ $parts[1] }++;
}

my $authors = Acme::CPANAuthors->new;

my $path = $ENV{HOME} . '/tmp/avatars/';

my $i = 0;

# Fetch the author avatars
for my $author ( sort keys %authors ) {
    $i++;
    $authors{$author} = $authors->avatar_url($author);
    my $status = getstore( $authors{$author}, $path . "$author.jpg" );
    print "$i. Author: $author avatar saved.\n";
    sleep 4;
last if $i >= 9;
}
