#!/usr/bin/env perl
use strict;
use warnings;

# Construct a collage of CPAN author gravatars.
# Write-up: http://techn.ology.net/making-an-image-map-of-cpan-authors/

# Examples:
# perl cpan-avatars 10      # A 10x10 collage starting at author 1
# perl cpan-avatars 3 1000  # A 3x3 collage starting at author 1000
# perl cpan-avatars 2 gene  # A 2x2 collage starting at author GENE

use File::Copy;
use File::Slurper 'write_text';
use HTTP::Simple;
use Imager;
use List::SomeUtils 'first_index';
use Mojo::DOM;
use Mojo::UserAgent;
use Parse::CPAN::Authors;

my $side  = shift || 3; # Number of images per side of the collage
my $start = shift || 1; # Where in the alphabetical order to begin the collage - number or author name
my $path  = shift || $ENV{HOME} . '/tmp/avatars/'; # Where our avatars, default, and the collage live

my $width = 130;            # Fixed avatar side pixel size
my $size  = $width * $side; # The width of the collage
my $max   = $side ** 2;     # Number of avatars to fetch

my $base = 'https://metacpan.org/author/';
my $cpan = 'http://www.cpan.org/authors/';
my $file = '01mailrc.txt.gz';

my %authors;

die "Path '$path' does not exist"
    unless -d $path;

get_file($cpan . $file, $file, "Saved $file");

my $pca = Parse::CPAN::Authors->new($file);

# Get each author metacpan url
for my $author ($pca->authors) {
    $authors{ $author->pauseid } = $base . $author->pauseid;
}

# Find the index of the given author name
if ($start =~ /^[A-Za-z]+$/) {
    my $author = $start;
    $start = first_index { CORE::fc($_) eq CORE::fc($start) } sort keys %authors;
    die "Author '$author' not found\n"
        if $start < 0;
    $start++;
}

my $i = 0;

# Remove authors that precede the given start
for my $author (sort keys %authors) {
    $i++;
    if ($i < $start) {
        delete $authors{$author};
    }
    else {
        last;
    }
}

die "No authors\n"
    if keys(%authors) < 1;

$i = 0; # reset the incrementer

# Fetch the author avatar images
for my $author (sort keys %authors) {
    $i++;
    sleep 4 unless $i == 1; # play nice

    my $ua = Mojo::UserAgent->new;
    my $tx = $ua->get($authors{$author});
    my $dom = Mojo::DOM->new($tx->res->body);
    my $img = $dom->find('img[alt="Author image"]')->[0]->attr('src');
    my $img_file = $path . $author;
    get_file($img, $img_file, "$i. Saved $img_file");

    last if $i >= $max;
}

# Build an HTML image map
my $html =<<'HTML';
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <title>CPAN Author Collage</title>
</head>
<body>
<img src="collage.jpg" alt="CPAN Author Collage" usemap="#collage">
<map name="collage">
HTML

# Instantiate a blank, square collage image
my $collage = Imager->new(xsize => $size, ysize => $size)
    or die "Can't create image: ", Imager->errstr;

$i = 0; # reset the incrementer
my $j = 0; # x coordinate iterator
my $k = 0; # y coordinate iterator

# Read the author files and paste them onto the collage
for my $author (sort keys %authors) {
    my $img_file = $path . $author;

    my $img = Imager->new;
    $img->read(file => $img_file)
        or die "Can't read $img_file: ", $img->errstr;

    unlink $img_file;

    if ($j >= $side) {
        $j = 0;
        $k++;
    }
    my $x0 = $j * $width;
    my $x1 = $x0 + $width;
    my $y0 = $k * $width;
    my $y1 = $y0 + $width;
#    print "[$i,$j,$k] [$x0,$y0] [$x1,$y1]\n";

    $html .= qq|<area shape="rect" coords="$x0,$y0,$x1,$y1" alt="$author" href="https://metacpan.org/author/$author" title="$author">\n|;

    $collage->paste(left => $x0, top => $y0, img => $img);

    $i++;
    $j++;

    last if $i >= $max;
}

# Save the collage
$file = $path . 'collage.jpg';
$collage->write(file => $file) or
    die "Can't write to $file: ", $collage->errstr;
print "Saved $file\n";

# Finish the HTML image map
$html .=<<'HTML';
</map>
</body>
</html>
HTML

$file = $path . 'collage.html';
write_text($file, $html);
print "Saved $file\n";

sub get_file {
    my ($url, $file, $msg) = @_;
    my $status = getstore($url, $file)
        or die "Can't getstore $url to $file: $!\n";
    if ($status == 200) {
        print "$msg\n";
    }
    else {
        die "Could not get $file from $url\n";
    }
}
