#!/usr/bin/env perl
use strict;
use warnings;

use MetaCPAN::Client ();

my $distro = shift || 'Lingua-EN-Opinion';
my $mcpan = MetaCPAN::Client->new;
my $release = $mcpan->release($distro);
my $size = $release->stat->{size};
print $size, "\n";

__END__
use Expect::Simple ();

my $module = shift || 'Lingua::EN::Opinion';

my $look = "cpanm --look $module";
my $du   = 'du -c';

my $exp = Expect::Simple->new({
    Cmd           => $look,
    Prompt        => '▸ ', # replace with your prompt
    DisconnectCmd => 'exit',
});

$exp->send($du);

my $output = $exp->before;

$output =~ /(\d+)\s+total/s;
my $size = $1;
print $size, "\n";
